project_name: social-workout
copy:
    files:
        - workout.db
pools:
    devices:
        - emulator-5556
        - emulator-5558
        - emulator-5560
        - emulator-5562
        - emulator-5564
hooks:
    post_create:
        - just db
pool_grow:
    devices: android-emulator
